### ISSUE TITLE
La calificación del lab sigue abierta en Coursera

### ISSUE THREAD

**Issue by engalejandrovargas** [MOOC-tutorials/git_web_practice#28]
Para estudiantes que tenemos correos ajenos a los andes, parece que el laboratorio se reporta abierto. Agradezco gestionen este issue para poder obtener el certificado. Saludos.

**Comment by engalejandrovargas** [comment]
Ya obtuve la calificación.

**Comment by JennyMedina123** [comment]
Yo aun no lo e podido obtener y ya hice los 2 talleres

**Comment by sergiovilla41** [comment]
Yo aun no lo e podido obtener y ya hice los 2 talleres
